version: "3.7"

networks:
  fabrica_escuela_net:
    driver: bridge

services:
  mysql:
    image: mysql:8.0.2
    container_name: mysql
    ports:
      - "3306:3306"
    restart: always
    networks:
      - fabrica_escuela_net
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_PASSWORD: 12345
      MYSQL_USER: user
      MYSQL_DATABASE: fabrica_escuela
    volumes:
      - ./mysql_data:/var/lib/mysql

#  backend-virtual:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: backend-virtual
#    restart: always
#    networks:
#      - fabrica_escuela_net
##    environment:
##      ...