#spring.application.name=backend-virtual
#
#  # Configuración de la conexión a la base de datos Oracle
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
#spring.datasource.username=SYSTEM
#spring.datasource.password=juanselm1q2w3e@
#spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
#
#  # Configuración del pool de conexiones
#spring.datasource.hikari.maximum-pool-size=5
#spring.datasource.hikari.connection-timeout=30000
#spring.datasource.hikari.idle-timeout=600000
#spring.datasource.hikari.pool-name=SpringBootOracleCP

# ----------------------------------------------------------------------------------------------------------------------
# APPLICATION
spring:
  application:
    name: fabrica-escuela-backend-virtual
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
# ----------------------------------------------------------------------------------------------------------------------
# SERVER
server:
  port: 8080
