#spring.application.name=backend-virtual
#
#  # Configuración de la conexión a la base de datos Oracle
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
#spring.datasource.username=SYSTEM
#spring.datasource.password=juanselm1q2w3e@
#spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
#
#  # Configuración del pool de conexiones
#spring.datasource.hikari.maximum-pool-size=5
#spring.datasource.hikari.connection-timeout=30000
#spring.datasource.hikari.idle-timeout=600000
#spring.datasource.hikari.pool-name=SpringBootOracleCP

# ----------------------------------------------------------------------------------------------------------------------
# APPLICATION
spring:
  devtools:
    livereload:
      enabled: ${DEVTOOLS_LIVERELOAD_ENABLED}
  # ----------------------------------------------------------------------------------------------------------------------
  # DATABASE
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DATABASE_DRIVER_CLASS_NAME}
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO}
    show-sql: ${JPA_SHOW_SQL}
    properties:
      hibernate:
        format_sql: ${JP_HIBERNATE_FORMAT_SQL}
    database: ${JPA_DATABASE}
    database-platform: ${JP_HIBERNATE_DATABASE_PLATFORM}
# ----------------------------------------------------------------------------------------------------------------------
# AUTHENTICATION & AUTHORIZATION
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      access-token:
        expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
      id-token:
        expiration: ${JWT_ID_TOKEN_EXPIRATION}
# ----------------------------------------------------------------------------------------------------------------------